# # BUILD
FROM node:16 as build

ARG environnement=production

WORKDIR /usr/local/app

COPY ./ /usr/local/app/

RUN npm install 
RUN npm run ng build lhyfe-portail -- --configuration=${environnement} --localize

# EXECUTION
FROM nginx:1

RUN sed -i '/    default_type  application\/octet-stream;/ a \
    map $http_accept_language $accept_language {\n\
            ~*^fr fr;\n\
            ~*^en en;\n\
    }\n' /etc/nginx/nginx.conf
RUN echo '\
server { \n\
    listen       80; \n\
    listen  [::]:80; \n\
    server_name  localhost; \n\
    \n\
    if ($accept_language ~ "^$") {\
        set $accept_language "en";\
    }\
    \n\
    rewrite ^/$ /$accept_language permanent;\n\
    \n\
    location ~ ^/(fr|en) { \n\
        root   /usr/share/nginx/html; \n\
        try_files $uri /$1/index.html?$args; \n\
    } \n\
    \n\
    error_page   500 502 503 504  /50x.html; \n\
    location = /50x.html { \n\
        root   /usr/share/nginx/html; \n\
    } \n\
} \n\
'> /etc/nginx/conf.d/default.conf

COPY --from=build /usr/local/app/dist/lhyfe-portail /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]